sudo: false
language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
# Load database schema before rake
before_script: bundle exec rake db:schema:load
# Test on all supported rails versions
gemfile:
  - gemfiles/rails4_2.gemfile
  - gemfiles/rails5_0.gemfile
  - gemfiles/rails5_1.gemfile
  - gemfiles/rails5_2.gemfile
matrix:
  exclude:
    - rvm: 2.2.7
      gemfile: gemfiles/rails5_2.gemfile
    - rvm: 2.3.4
      gemfile: gemfiles/rails4_2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails4_2.gemfile
